const vanillaItems = [
  {
    id: 0,
    name: "Wood",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/vanilla-icons/wood.png"
  },
  {
    id: 1,
    name: "Cotton",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/vanilla-icons/cotton.png"
  },
  {
    id: 2,
    name: "Cooper Bar",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/blacksmithing-icons/CooperBar.icon.png"
  },
  {
    id: 3,
    name: "Iron Bar",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/blacksmithing-icons/IronBar.icon.png"
  },
  {
    id: 4,
    name: "Tin Bar",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 2,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/blacksmithing-icons/TinBar.icon.png"
  },
  {
    id: 5,
    name: "Cooper ore",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/blacksmithing-icons/copper_ore.png"
  },
  {
    id: 6,
    name: "Iron ore",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/blacksmithing-icons/iron_ore.png"
  },
  {
    id: 7,
    name: "Tin ore",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/blacksmithing-icons/tin_ore.png"
  },
  {
    id: 8,
    name: "Coal",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/blacksmithing-icons/coal.png"
  },
  {
    id: 9,
    name: "Wood Boards",
    descript: "",
    category: "vanilla",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 0,
    src: "../img/vanilla-icons/wood_boards.png"
  },
  {
    id: 10,
    name: "Light Cotton Fabric",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 203,
    src: "../img/tailoring-Icons/light_cotton_fabric.png"
  },
  {
    id: 11,
    name: "Thread",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 3,
    quantity: 1,
    xp: 453,
    src: "../img/tailoring-icons/thread.png"
  },
  {
    id: 12,
    name: "Heavy Cotton Fabric",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 9,
    quantity: 1,
    xp: 655,
    src: "../img/tailoring-icons/heavy_cotton_fabric.png"
  },
  {
    id: 13,
    name: "Rodent Pelt",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 655,
    src: "../img/vanilla-icons/rodent_pelt.png"
  },
  {
    id: 14,
    name: "Oak Log",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 655,
    src: "../img/vanilla-icons/oak_log.png"
  },
  {
    id: 15,
    name: "Pine Log",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 655,
    src: "../img/vanilla-icons/pine_log.png"
  },
  {
    id: 16,
    name: "Wood Boards",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 655,
    src: "../img/vanilla-icons/wood_boards.png"
  },
  {
    id: 17,
    name: "Oak Boards",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 655,
    src: "../img/vanilla-icons/Oak_Boards.png"
  },
  {
    id: 18,
    name: "Pine Boards",
    descript: "",
    category: "Items",
    recipe: null,
    tier: 1,
    level: 1,
    quantity: 1,
    xp: 655,
    src: "../img/vanilla-icons/Pine_Boards.png"
  },
]

export { vanillaItems }